### ISSUE TITLE
big omega -extension for firefox

### ISSUE THREAD

**Issue by aniketraz** [codedecks-in/Big-Omega-Extension#33]

**Comment by GouravRusiya30** [comment]
We have published the Add-on for Firefox today & it's in review state currently
<img width="898" alt="Screenshot 2023-04-05 at 10 17 49 PM" src="https://user-images.githubusercontent.com/13219295/230149160-f732a167-f9ae-4a37-ab6b-5c15b8f82dc8.png">

**Comment by GouravRusiya30** [comment]
Big Ω - Enhance Leetcode experience by Big Omega Team
https://addons.mozilla.org/en-US/firefox/addon/big-omega-extension/

**Comment by GouravRusiya30** [comment]
### Mozilla Add-ons: Big Ω - Enhance Leetcode experience 1.0.2 Approved ✅

#### Big Ω - Enhance Leetcode experience 1.0.2, has been approved and is now available for download in our gallery at https://addons.mozilla.org/addon/big-omega-extension/
