### ISSUE TITLE
Show Question list for a specific Company

### ISSUE THREAD

**Issue by shubh4122** [codedecks-in/Big-Omega-Extension#41]
When a question is clicked upon, we see list of companies it was asked in.
What i propose is, when a user clicks on any of those company tags the user must be directed to a page/doc/somewhere where he gets access to question list asked in that specific company he clicked the tag of.

This will help users to get to know what other questions that particular company has asked in past.

**Comment by GouravRusiya30** [comment]
@shubh4122 Thanks for the Feature request. We will soon start picking this up.

**Comment by Rishabh-Pahwa** [comment]
Good idea!. I'll try to implement this.

**Comment by omkarajagunde** [comment]
Yeah we want to work on it, but we are having hard time coming up the design of where to show the problem list on click of tag, will we open a pop up or redirect to our page, if we redirect to our page where will we host it etc...

All ideas of how to show it are welcomed!

**Comment by Rishabh-Pahwa** [comment]
I was thinking of creating a dialog box(pop-up) to show all the links. And was also considering [Render.com](https://render.com/docs/deploy-node-express-app) to host a new page(if required), but still need to check if it is supported. Was stuck on the build issue for the past week will work on this once I figure that out.

**Comment by omkarajagunde** [comment]
I have pushed a Pr to solve exact same issue, @GouravRusiya30 @Rishabh-Pahwa please have a look at Pr - #53

**Comment by omkarajagunde** [comment]
@shubh4122

**Comment by GouravRusiya30** [comment]
Closing this issue since PR is merged to main branch

**Comment by shubh4122** [comment]
Thank you for the feature! It'll help a lot.
