### ISSUE TITLE
Company tag readability

### ISSUE THREAD

**Issue by Rishabh-Pahwa** [codedecks-in/Big-Omega-Extension#42]
The background color and font color needs to be changed as this light grey font color has a bit of readability issues. I would suggest the background color be changed to yellow(from light blue), it will match the leetcode theme & the font color to be changed to black for better readability.

Yellow color Hex code (same as leetcode) - ffa116

Atleast bold the font that would also be better.
![image](https://user-images.githubusercontent.com/74728374/231274612-9bfdae3d-9c7c-4cd4-a238-39a2e409d7d2.png)

**Comment by GouravRusiya30** [comment]
Thanks @Rishabh-Pahwa for creating this issue.
But this doesn't looks a `Priority` feature for me. If we will receive more feedbacks on this similar UX changes, we will make this change.

But for now, this isn't a Priority for us !!!

**Comment by 9520prashant** [comment]
I think this issue is very obvious, we have to change the company tags according to leetcode UI. I wanna work on this issue can you please assign this issue to me.

**Comment by 9520prashant** [comment]
@GouravRusiya30 You can See the Difference between the Amazon Tag and other Tags

![Screenshot (187)](https://user-images.githubusercontent.com/99237795/235286502-42a36845-67cf-4e11-9103-178cd27c8a84.png)

**Comment by GouravRusiya30** [comment]
Done, go ahead and create the Pull request for the change.

**Comment by 9520prashant** [comment]
Sure, stated working on it

**Comment by 9520prashant** [comment]
Hey @GouravRusiya30 @Rishabh-Pahwa  How can test this extension in my local environment

**Comment by Rishabh-Pahwa** [comment]
@9520prashant Checkout the README file

**Comment by 9520prashant** [comment]
@GouravRusiya30 @Rishabh-Pahwa Kindly review my PR and if there will some mistake then please let me know I will correct.
