### ISSUE TITLE
Doesn't show company tags when switched to old ui of leetcode

### ISSUE THREAD

**Issue by akhilr007** [codedecks-in/Big-Omega-Extension#44]

**Comment by akhilr007** [comment]
<img width="1434" alt="Screenshot 2023-04-14 at 1 06 13 PM" src="https://user-images.githubusercontent.com/46931704/231976150-86c250af-743b-44d1-9a42-8bca41b35f74.png">

**Comment by GouravRusiya30** [comment]
This is fixed and we have pushed the changes to Chrome Webstore, will be available in 2 days.
