### ISSUE TITLE
Problem while npm run build

### ISSUE THREAD

**Issue by Rishabh-Pahwa** [codedecks-in/Big-Omega-Extension#45]
I wanted to contribute towards #41 'Show company specific problems' but when I cloned the repo and tried to build I am unable to create the zipped folder. I have only changed export-> set & mv -> move in the package.json file as I am on a windows machine.
I get an error as  A duplicate file name exists, or the file cannot be found. Attached the error ss, build folder and static folder.
---WINDOWS EDITS
![image](https://user-images.githubusercontent.com/74728374/232615874-a2864a97-aaed-423c-9a6e-5bb6fd52f8f4.png)

----ERROR
![image](https://user-images.githubusercontent.com/74728374/232614971-5a899e76-57f0-4097-a079-b029adcb53d3.png)
----OUTPUT BUILD FOLDER
![image](https://user-images.githubusercontent.com/74728374/232615275-785093c3-88b1-43cd-b218-e077f93c438d.png)
-----STATIC FOLDER
![image](https://user-images.githubusercontent.com/74728374/232615391-ccc43961-c307-476b-9763-8d84e0d9c54b.png)
![image](https://user-images.githubusercontent.com/74728374/232615448-a9980162-a03d-446f-9500-79df02e0d64f.png)

**Comment by DarshanDixit05** [comment]
I want to work on this issue.

**Comment by GouravRusiya30** [comment]
Please don't raise irrelevant issues.

**Comment by Rishabh-Pahwa** [comment]
It isn't an irrelevant issue,  was just asking because I thought there might be something else that we need to change for windows as you have written it on a Mac. And I was only trying to compile it myself as I wanted to contribute to the project.

**Comment by GouravRusiya30** [comment]
Sure @Rishabh-Pahwa 
Please try to debug and make it work for Windows. I am sure if you tweak you can find out the way. If it works for you then please add PR with updated README.
Thanks !!!

**Comment by omkarajagunde** [comment]
@Rishabh-Pahwa you can remove `&& npm run zip-build` from build command as its not a necessary thing to zip build folder

also i feel move syntax and linux slash vs windows slash is causing this problem of move not getting hold of correct files path to move (i mean the syntax of command as per the windows procedure), can you try to check move windows help manual and fix it?

**Comment by Rishabh-Pahwa** [comment]
Finally figured this out, build successful. Thanks mate!
Getting only one minor error, I think this is also related to mac as I tested the extension & it works perfectly fine.

**Comment by Rishabh-Pahwa** [comment]
@GouravRusiya30 Attached the screenshot of all the changes required for a windows machine. Should I create a PR with a new package.json file or just add this edited part to the README.md file?

**Comment by Rishabh-Pahwa** [comment]
> Sure @Rishabh-Pahwa Please try to debug and make it work for Windows. I am sure if you tweak you can find out the way. If it works for you then please add PR with updated README. Thanks !!!
Attached the screenshot of all the changes required for a windows machine. Should I create a PR with a new package.json file or just add this edited part to the README.md file?

**Comment by Rishabh-Pahwa** [comment]
@GouravRusiya30 Attached the screenshot of all the changes required for a windows machine. Should I create a PR with a new package.json file or just add this edited part to the README.md file?
