### ISSUE TITLE
The pop-up which provides an option to ENABLE or DISABLE tag doesn't collapse until we hover over that pop-up.

### ISSUE THREAD

**Issue by DarshanDixit05** [codedecks-in/Big-Omega-Extension#48]
It's been a while since I'm using this Chrome extension. The pop-up which provides an option to ENABLE or DISABLE tag doesn't collapse until we hover over that pop-up.

I don't know but UX isn't good in this scenario. Being a user I don't want to hover over the same tab on every problem. This repeats even if I reload the page.  If each reload or a new problem costs the user a hover on the same tab then eventually user experience decreases.

**I want to work on this issue.**

<img width="959" alt="Screenshot 2023-04-21 005722" src="https://user-images.githubusercontent.com/76871537/233470591-f1b8ab02-0fb7-45d1-b513-22b061d29f36.png">

**Comment by sherlockhoe90** [comment]
Not an inconvenience to me. If it ain't broken, no need to fix it.

**Comment by omkarajagunde** [comment]
@DarshanDixit05 this is kept open by default, so that the users know this plugin is having some effect on the page
