### ISSUE TITLE
Submit button overflows in macBook

### ISSUE THREAD

**Issue by Aditya1101999** [codedecks-in/Big-Omega-Extension#68]

**Comment by Cipher-08** [comment]
Hello Admin , I want to contribute to this issue !

**Comment by st17931** [comment]
@Aditya1101999 can you pls add some screenshot for the problem and steps to reproduce in macBook pls??

**Comment by Aditya1101999** [comment]
Issue resolved.
Thanks

**Comment by st17931** [comment]
@GouravRusiya30 we can close this issue now we dont have such issue attaching screenshot
![Image 20-05-23 at 12 00 AM](https://github.com/codedecks-in/Big-Omega-Extension/assets/58268246/fbf3a924-62fc-43e3-8ca5-10dbe7c3a6f7)
